export const cars = [
  {
    city_mpg: 25,
    class: "compact car",
    combination_mpg: 29,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "kia",
    model: "ceed",
    transmission: "a",
    year: 2015,
  },
  {
    city_mpg: 25,
    class: "compact car",
    combination_mpg: 29,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "bmw",
    model: "x5",
    transmission: "m",
    year: 2021,
  },
  {
    city_mpg: 31,
    class: "compact car",
    combination_mpg: 35,
    cylinders: 4,
    displacement: 2,
    drive: "fwd",
    fuel_type: "diesel",
    highway_mpg: 41,
    make: "volkswagen",
    model: "golf",
    transmission: "a",
    year: 2015,
  },
  {
    city_mpg: 25,
    class: "compact car",
    combination_mpg: 29,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 35,
    make: "alfa romeo",
    model: "giulia",
    transmission: "a",
    year: 2015,
  },
  {
    city_mpg: 30,
    class: "compact car",
    combination_mpg: 35,
    cylinders: 4,
    displacement: 2,
    drive: "fwd",
    fuel_type: "diesel",
    highway_mpg: 43,
    make: "alfa romeo",
    model: "stelvio",
    transmission: "m",
    year: 2020,
  },
  {
    city_mpg: 126,
    class: "compact car",
    combination_mpg: 116,
    displacement: 2,
    cylinders: 4,
    drive: "fwd",
    fuel_type: "electricity",
    highway_mpg: 105,
    make: "alfa romeo",
    model: "giulietta",
    transmission: "a",
    year: 2020,
  },
  {
    city_mpg: 23,
    class: "compact car",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 2,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "volkswagen",
    model: "tiguan",
    transmission: "a",
    year: 2015,
  },
  {
    city_mpg: 31,
    class: "small station wagon",
    combination_mpg: 35,
    cylinders: 4,
    displacement: 2,
    drive: "fwd",
    fuel_type: "diesel",
    highway_mpg: 40,
    make: "volkswagen",
    model: "golf sportwagen",
    transmission: "a",
    year: 2015,
  },
  {
    city_mpg: 30,
    class: "small station wagon",
    combination_mpg: 35,
    cylinders: 4,
    displacement: 2,
    drive: "fwd",
    fuel_type: "diesel",
    highway_mpg: 42,
    make: "volkswagen",
    model: "golf sportwagen",
    transmission: "m",
    year: 2015,
  },
  {
    city_mpg: 25,
    class: "small station wagon",
    combination_mpg: 29,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 34,
    make: "volkswagen",
    model: "golf sportwagen",
    transmission: "a",
    year: 2015,
  },
  {
    city_mpg: 25,
    class: "small station wagon",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 35,
    make: "volkswagen",
    model: "golf sportwagen",
    transmission: "m",
    year: 2015,
  },
  {
    city_mpg: 25,
    class: "small station wagon",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 35,
    make: "volkswagen",
    model: "passat",
    transmission: "m",
    year: 2015,
  },
  {
    city_mpg: 25,
    class: "small station wagon",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 35,
    make: "volkswagen",
    model: "t-roc",
    transmission: "a",
    year: 2015,
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
